cv: 5
estimators:
  lr:
    C: 1.0
    class_weight: null
    dual: false
    fit_intercept: true
    intercept_scaling: 1
    l1_ratio: null
    max_iter: 1000
    multi_class: deprecated
    n_jobs: null
    penalty: l2
    random_state: null
    solver: lbfgs
    tol: 0.0001
    verbose: 0
    warm_start: false
  svc:
    C: 100
    break_ties: false
    cache_size: 200
    class_weight: null
    coef0: 0.0
    decision_function_shape: ovr
    degree: 3
    gamma: 0.001
    kernel: rbf
    max_iter: -1
    probability: true
    random_state: null
    shrinking: true
    tol: 0.001
    verbose: false
  xgb:
    base_score: null
    booster: null
    callbacks: null
    colsample_bylevel: null
    colsample_bynode: null
    colsample_bytree: 0.8
    device: null
    early_stopping_rounds: null
    enable_categorical: false
    eval_metric: logloss
    feature_types: null
    feature_weights: null
    gamma: 1
    grow_policy: null
    importance_type: null
    interaction_constraints: null
    learning_rate: 0.1
    max_bin: null
    max_cat_threshold: null
    max_cat_to_onehot: null
    max_delta_step: null
    max_depth: 3
    max_leaves: null
    min_child_weight: null
    missing: .nan
    monotone_constraints: null
    multi_strategy: null
    n_estimators: 150
    n_jobs: null
    num_parallel_tree: null
    objective: binary:logistic
    random_state: 42
    reg_alpha: 0.1
    reg_lambda: 2
    sampling_method: null
    scale_pos_weight: null
    subsample: 1.0
    tree_method: null
    use_label_encoder: false
    validate_parameters: null
    verbosity: null
final_estimator:
  C: 1.0
  class_weight: null
  dual: false
  fit_intercept: true
  intercept_scaling: 1
  l1_ratio: null
  max_iter: 100
  multi_class: deprecated
  n_jobs: null
  penalty: l2
  random_state: null
  solver: lbfgs
  tol: 0.0001
  verbose: 0
  warm_start: false
